# Generated by Django 2.1.3 on 2018-12-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='max_num_of_shooting',
            new_name='shooting_num',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='max_num_of_shooting_with_finder',
            new_name='shooting_num_with_finder',
        ),
    ]
