# Generated by Django 2.1.3 on 2019-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='review_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
