# Generated by Django 2.1.3 on 2019-01-22 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
