# Generated by Django 2.1.3 on 2019-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20181223_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='amazon_link',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='rakuten_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
