# Generated by Django 2.1.3 on 2019-01-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20190105_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='camera.Camera')),
                ('hashtag', models.IntegerField(verbose_name='ハッシュタグ数')),
                ('hashtag_increase_week', models.IntegerField(verbose_name='週間ハッシュタグ増加数')),
            ],
        ),
    ]
