# Generated by Django 2.1.3 on 2019-01-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag_increase_week',
            new_name='week_increase',
        ),
    ]
