# Generated by Django 2.1.1 on 2018-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='bluetooth',
            field=models.CharField(max_length=20),
        ),
    ]
