# Generated by Django 2.1.1 on 2018-11-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181112_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='camera',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='search.Camera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
