# Generated by Django 2.1.3 on 2019-01-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='max_f_value',
            new_name='max_f_value_tele',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='min_f_value',
            new_name='min_f_value_tele',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='newest_open_month',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='newest_open_year',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='oldest_open_month',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='oldest_open_year',
        ),
        migrations.AddField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='rank',
            name='max_open_date',
            field=models.DateField(null=True, verbose_name='max_open_date'),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_open_date',
            field=models.DateField(null=True, verbose_name='min_open_date'),
        ),
        migrations.AddField(
            model_name='rank',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='updated_at'),
        ),
    ]
