# Generated by Django 2.1.3 on 2018-12-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rank_target_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='anti_shake',
            field=models.BooleanField(null=True, verbose_name='anti_shake'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='bluetooth',
            field=models.BooleanField(null=True, verbose_name='bluetooth'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='camera_type_id',
            field=models.IntegerField(null=True, verbose_name='camera_type_id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='finder_id',
            field=models.IntegerField(null=True, verbose_name='finder_id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='five_axis_anti_shake',
            field=models.BooleanField(null=True, verbose_name='five_axis_anti_shake'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='four_k',
            field=models.BooleanField(null=True, verbose_name='four_k'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='frame_id',
            field=models.IntegerField(null=True, verbose_name='frame_id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='gps',
            field=models.BooleanField(null=True, verbose_name='gps'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='maker_id',
            field=models.IntegerField(null=True, verbose_name='maker_id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_continuous_shooting_performance',
            field=models.FloatField(null=True, verbose_name='continuous_shooting_performance'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_depth',
            field=models.FloatField(null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_f_value',
            field=models.FloatField(null=True, verbose_name='f_value'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_f_value_wide',
            field=models.FloatField(null=True, verbose_name='f_value_wide'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_focus',
            field=models.IntegerField(null=True, verbose_name='focus'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_height',
            field=models.FloatField(null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_iso',
            field=models.IntegerField(null=True, verbose_name='iso'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_monitor_size',
            field=models.FloatField(null=True, verbose_name='monitor_size'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_nearest_shot',
            field=models.FloatField(null=True, verbose_name='nearest_shot'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_num_of_shooting',
            field=models.IntegerField(null=True, verbose_name='num_of_shooting'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_num_of_shooting_with_finder',
            field=models.IntegerField(null=True, verbose_name='num_of_shooting_with_finder'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_pixel',
            field=models.IntegerField(null=True, verbose_name='pixel'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_shutter_speed',
            field=models.CharField(max_length=50, null=True, verbose_name='shutter_speed'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_water_depth',
            field=models.IntegerField(null=True, verbose_name='water_depth'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_weight',
            field=models.FloatField(null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_width',
            field=models.FloatField(null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_zoom',
            field=models.FloatField(null=True, verbose_name='zoom'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_continuous_shooting_performance',
            field=models.FloatField(null=True, verbose_name='continuous_shooting_performance'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_depth',
            field=models.FloatField(null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_f_value',
            field=models.FloatField(null=True, verbose_name='f_value'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_f_value_wide',
            field=models.FloatField(null=True, verbose_name='f_value_wide'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_focus',
            field=models.IntegerField(null=True, verbose_name='focus'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_height',
            field=models.FloatField(null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_iso',
            field=models.IntegerField(null=True, verbose_name='iso'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_monitor_pixel',
            field=models.FloatField(null=True, verbose_name='monitor_pixel'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_monitor_size',
            field=models.FloatField(null=True, verbose_name='monitor_size'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_nearest_shot',
            field=models.FloatField(null=True, verbose_name='nearest_shot'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_nearest_shot_with_macro_mode',
            field=models.FloatField(null=True, verbose_name='nearest_shot_with_macro_mode'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_num_of_shooting',
            field=models.IntegerField(null=True, verbose_name='num_of_shooting'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_num_of_shooting_with_finder',
            field=models.IntegerField(null=True, verbose_name='num_of_shooting_with_finder'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_pixel',
            field=models.IntegerField(null=True, verbose_name='pixel'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_shutter_speed',
            field=models.CharField(max_length=50, null=True, verbose_name='shutter_speed'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_water_depth',
            field=models.IntegerField(null=True, verbose_name='water_depth'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_weight',
            field=models.FloatField(null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_width',
            field=models.FloatField(null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_zoom',
            field=models.FloatField(null=True, verbose_name='zoom'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='move_panel',
            field=models.BooleanField(null=True, verbose_name='move_panel'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='newest_open_month',
            field=models.IntegerField(null=True, verbose_name='newest_open_month'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='newest_open_year',
            field=models.IntegerField(null=True, verbose_name='newest_open_year'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='oldest_open_month',
            field=models.IntegerField(null=True, verbose_name='oldest_open_month'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='oldest_open_year',
            field=models.IntegerField(null=True, verbose_name='oldest_open_year'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='selfie',
            field=models.BooleanField(null=True, verbose_name='selfie'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='super_wide',
            field=models.BooleanField(null=True, verbose_name='super_wide'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='target_keyword',
            field=models.CharField(max_length=255, null=True, verbose_name='target_keyword'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='touch_panel',
            field=models.BooleanField(null=True, verbose_name='touch_panel'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='waterploof',
            field=models.BooleanField(null=True, verbose_name='waterploof'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='wifi',
            field=models.BooleanField(null=True, verbose_name='wifi'),
        ),
    ]
