# Generated by Django 2.1.3 on 2019-01-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20190109_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='max_focus',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='min_focus',
        ),
        migrations.AddField(
            model_name='rank',
            name='max_focus_tele',
            field=models.IntegerField(null=True, verbose_name='focus_tele'),
        ),
        migrations.AddField(
            model_name='rank',
            name='max_focus_wide',
            field=models.IntegerField(null=True, verbose_name='focus_wide'),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_focus_tele',
            field=models.IntegerField(null=True, verbose_name='focus_tele'),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_focus_wide',
            field=models.IntegerField(null=True, verbose_name='focus_wide'),
        ),
    ]
