# Generated by Django 2.1.3 on 2019-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20190109_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='max_focus_tele',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='max_focus_wide',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='min_focus_tele',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='min_focus_wide',
        ),
        migrations.AddField(
            model_name='rank',
            name='max_focus',
            field=models.IntegerField(null=True, verbose_name='max_focus'),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_focus',
            field=models.IntegerField(null=True, verbose_name='min_focus'),
        ),
    ]
