# Generated by Django 2.1.3 on 2018-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20181204_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='max_num_of_shooting',
            new_name='max_shooting_num',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='max_num_of_shooting_with_finder',
            new_name='max_shooting_num_with_finder',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='min_num_of_shooting',
            new_name='min_shooting_num',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='min_num_of_shooting_with_finder',
            new_name='min_shooting_num_with_finder',
        ),
        migrations.AddField(
            model_name='rank',
            name='max_nearest_shot_with_macro_mode',
            field=models.FloatField(null=True, verbose_name='nearest_shot_with_macro_mode'),
        ),
    ]
