# Generated by Django 2.1.3 on 2018-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20181208_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='max_monitor_pixel',
            field=models.FloatField(null=True, verbose_name='monitor_pixel'),
        ),
    ]
